import assert from "node:assert/strict";
import fs from "node:fs";

const read = (path) => fs.readFileSync(path, "utf8");

const legacy = read("src/v8/family-stock-selection-v15.ts");
assert.match(legacy, /FAMILY_STOCK_SELECTION_VERSION = "family-stock-selection\/production-v1\.6\.0"/);
assert.match(legacy, /tryFugleTickersMisOtc/);
assert.match(legacy, /FINMIND_FALLBACK/);

const selector = read("src/v8/family-stock-selection-v17.ts");
assert.match(selector, /FAMILY_STOCK_SELECTION_VERSION = "family-stock-selection\/production-v1\.7\.0"/);
assert.match(selector, /openapi\.twse\.com\.tw\/v1\/exchangeReport\/STOCK_DAY_ALL/);
assert.match(selector, /mopsfin\.twse\.com\.tw\/opendata\/t187ap03_O\.csv/);
assert.match(selector, /mis\.twse\.com\.tw\/stock\/api\/getStockInfo\.jsp/);
assert.match(selector, /MOPSFIN_COMPANY_MASTER_MIS_OTC/);
assert.match(selector, /MOPSFIN TPEx company master \+ TWSE MIS OTC quotes/);
assert.match(selector, /loadTpexCompanyUniverse/);
assert.match(selector, /loadTpexMopsMis/);
assert.match(selector, /loadRobustUniverse/);
assert.match(selector, /parseCsv/);
assert.match(selector, /MIS_BATCH_SIZE = 100/);
assert.match(selector, /otc_\$\{symbol\}\.tw/);
assert.match(selector, /FUGLE_HISTORICAL/);
assert.match(selector, /\/historical\/candles\/\$\{symbol\}/);
assert.match(selector, /finmind_required_for_market_coverage: false/);
assert.match(selector, /fugle_required_for_market_coverage: false/);
assert.match(selector, /runLegacyFamilyStockSelection/);
assert.match(selector, /LEGACY_V15_PROVIDER_CHAIN/);
assert.match(selector, /GREEN_RESEARCH/);
assert.match(selector, /YELLOW_WAIT/);
assert.match(selector, /不追價/);
assert.doesNotMatch(selector, /news/i);

const entry = read("src/production-entry.ts");
assert.match(entry, /\.\/v8\/family-stock-selection-v17/);
assert.match(entry, /FAMILY_RUNTIME_RELEASE = "family-production-runtime\/1\.8\.0"/);
assert.match(entry, /FAMILY_CACHE_SCHEMA = "family-selection-lkg\/v1"/);
assert.match(entry, /FAMILY_CACHE_MAX_AGE_MS = 7 \* 24 \* 60 \* 60 \* 1000/);
assert.match(entry, /family-selection:lkg:v1/);
assert.match(entry, /putFamilySelectionCache/);
assert.match(entry, /getFamilySelectionCache/);
assert.match(entry, /cachedFallbackResult/);
assert.match(entry, /refreshDefaultFamilyCache/);
assert.match(entry, /ctx\.waitUntil\(putFamilySelectionCache/);
assert.match(entry, /ctx\.waitUntil\(refreshDefaultFamilyCache/);
assert.match(entry, /cache_fallback/);
assert.match(entry, /\/health\/family-cache/);
assert.match(entry, /isFamilyStockSelectionQuery/);
assert.match(entry, /\/api\/family\/query/);
assert.match(entry, /\/health\/family-selection-data/);
assert.match(entry, /diagnoseFamilySelectionData\(env\)/);
assert.match(entry, /MOM_GPT_API_KEY/);
assert.match(entry, /OAUTH_KV\.put/);
assert.match(entry, /OAUTH_KV\.get/);
assert.match(entry, /legacyOauthEntry\.fetch/);
assert.match(entry, /family_stock_selection/);
assert.match(entry, /資料鏈失敗/);
assert.match(entry, /新聞硬湊候選股/);
assert.match(entry, /最後一次成功的完整選股結果/);

const wrangler = read("wrangler.jsonc");
assert.match(wrangler, /"main": "src\/production-entry\.ts"/);
assert.match(wrangler, /"binding": "OAUTH_KV"/);
assert.match(wrangler, /"name": "FAMILY_MCP_OBJECT"/);
assert.match(wrangler, /"new_sqlite_classes": \["FamilyMCP"\]/);
assert.match(wrangler, /"tag": "v2"/);
assert.match(wrangler, /"database_id": "18673f52-c286-49f3-a82c-bf67d0593611"/);
assert.doesNotMatch(wrangler, /RESEARCH_BUCKET/);

console.log("Production family selector v1.7 MOPSFIN+MIS + runtime v1.8 LKG cache contract passed");