import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const read=(p:string)=>fs.readFileSync(path.join(root,p),"utf8");
assert.equal(fs.existsSync(path.join(root,".github/workflows/market-data-github-archive.yml")),false);
const store=read("src/v6/github-data-store.ts");assert.match(store,/keywayk09\/tv-papertrader/);assert.match(store,/DEFAULT_GITHUB_DATA_BRANCH = "main"/);
const capture=read("scripts/capture-tw-market-data.ts");assert.match(capture,/https:\/\/www\.tpex\.org\.tw\/openapi\/v1\/tpex_3insti_daily_trading/);assert.match(capture,/tpex_mainboard_margin_balance/);assert.match(capture,/tpex_margin_sbl/);assert.match(capture,/tpex_short_sell/);assert.match(capture,/source_date_mismatch/);assert.match(capture,/sha256|sha\(/i);assert.match(capture,/dueLayerKeys/);assert.match(capture,/rawCapture/);assert.match(capture,/validateDate/);
assert.equal(fs.existsSync(path.join(root,"src/v6/github-canonical-sync.ts")),false);assert.equal(fs.existsSync(path.join(root,"src/v6/tpex-official-relay.ts")),false);assert.equal(fs.existsSync(path.join(root,"src/v6/tpex-market-data-backfill.ts")),false);assert.equal(fs.existsSync(path.join(root,".github/workflows/tpex-official-relay.yml")),false);
console.log("P19 unified official incremental market-data source + tv-papertrader canonical store tests passed");
