import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  institutionalWindows, marginWindows, normalizeTpexInstitutional, normalizeTpexMargin, normalizeTpexSblShortSale,
  normalizeTradeDate, normalizeTwseInstitutional, normalizeTwseMargin, normalizeTwseSecuritiesLending, normalizeTwseSblShortSale,
  securitiesLendingWindows, sblShortSaleWindows, type InstitutionalRow, type MarginRow,
} from "../src/v6/tw-market-data.ts";
assert.equal(normalizeTradeDate("115/08/19"),"2026-08-19");assert.equal(normalizeTradeDate("1150819"),"2026-08-19");assert.equal(normalizeTradeDate("20260819"),"2026-08-19");
const ti=normalizeTwseInstitutional({stat:"OK",date:"20260819",fields:["證券代號","證券名稱","外陸資買賣超股數(不含外資自營商)","投信買賣超股數","自營商買賣超股數","三大法人買賣超股數"],data:[["2330","台積電","1,000","200","-50","1,150"]]},"2026-08-19");assert.equal(ti[0].total_net_shares,1150);
const oi=normalizeTpexInstitutional([{Date:"1150819",SecuritiesCompanyCode:"6488",CompanyName:"環球晶","ForeignInvestorsInclude MainlandAreaInvestors-Difference":"2,000","SecuritiesInvestmentTrustCompanies-Difference":"-100","Dealers-Difference":"50",TotalDifference:"1,950"}],"2026-08-19");assert.equal(oi[0].market,"otc");assert.equal(oi[0].total_net_shares,1950);
const tm=normalizeTwseMargin({stat:"OK",date:"20260819",tables:[{title:"融資融券彙總",fields:["證券代號","證券名稱","融資前日餘額","融資今日餘額","融券前日餘額","融券今日餘額"],data:[["2330","台積電","10,000","10,500","800","750"]]}]},"2026-08-19");assert.equal(tm[0].margin_balance_change_lots,500);assert.equal(tm[0].short_balance_change_lots,-50);
const om=normalizeTpexMargin([{Date:"1150819",SecuritiesCompanyCode:"6488",CompanyName:"環球晶",MarginPurchaseBalancePreviousDay:"1,000",MarginPurchaseBalance:"1,100",ShortSaleBalancePreviousDay:"90",ShortSaleBalance:"120"}],"2026-08-19");assert.equal(om[0].margin_balance_change_lots,100);assert.equal(om[0].short_balance_change_lots,30);
const lend=normalizeTwseSecuritiesLending({date:"20260819",fields:["證券代號","證券名稱","前日借券餘額(1)股","本日異動股借券(2)","本日異動股還券(3)","本日借券餘額股(4)=(1)+(2)-(3)","本日收盤價(5)單位：元","借券餘額市值單位：元(6)=(4)*(5)","市場別"],data:[["2330","台積電","1,000","300","100","1,200","1000","1,200,000","集中市場"],["6488","環球晶","500","100","20","580","500","290,000","櫃買市場"]]},"2026-08-19");assert.equal(lend[0].borrowed_shares,300);assert.equal(lend[0].returned_shares,100);assert.equal(lend[1].market,"otc");
const twSbl=normalizeTwseSblShortSale({date:"20260819",fields:["代號","名稱","前日餘額","賣出","買進","現券","今日餘額","次一營業日限額","前日餘額","當日賣出","當日還券","當日調整","當日餘額","次一營業日可限額","備註"],data:[["2330","台積電","0","0","0","0","0","0","10,000","2,000","500","100","11,600","20,000",""]]},"2026-08-19");assert.equal(twSbl[0].sold_shares,2000);assert.equal(twSbl[0].returned_shares,500);assert.equal(twSbl[0].balance_shares,11600);
const otcSbl=normalizeTpexSblShortSale([{Date:"1150819",SecuritiesCompanyCode:"6488",CompanyName:"環球晶",SecuritiesBorrowingBalancePreviousDay:"10000",SecuritiesBorrowingSale:"2000",SecuritiesBorrowingReturn:"500",SecuritiesBorrowingAdjustment:"100",SecuritiesBorrowingBalanceOfTheMarketDay:"11600",AvailableVolumesForSBLShortSale:"20000"}],[{Date:"1150819",SecuritiesCompanyCode:"6488",CompanyName:"環球晶",SBLVolume:"3",SBLAmount:"1500000"}],"2026-08-19");assert.equal(otcSbl[0].sold_volume_shares,3000);assert.equal(otcSbl[0].sold_amount,1500000);
const instRows:InstitutionalRow[]=Array.from({length:20},(_,i)=>({trade_date:`2026-07-${String(i+1).padStart(2,"0")}`,symbol:"2330",name:"台積電",market:"listed",foreign_net_shares:i+1,trust_net_shares:2,dealer_net_shares:-1,total_net_shares:i+2,source:"fixture",source_priority:"OFFICIAL"}));assert.equal((institutionalWindows(instRows) as any)["3d"].foreign_net_shares,57);
const marginRows:MarginRow[]=Array.from({length:20},(_,i)=>({trade_date:`2026-07-${String(i+1).padStart(2,"0")}`,symbol:"2330",name:"台積電",market:"listed",margin_previous_balance_lots:1000+i,margin_balance_lots:1001+i,margin_balance_change_lots:1,short_previous_balance_lots:100+i,short_balance_lots:102+i,short_balance_change_lots:2,source:"fixture",source_priority:"OFFICIAL"}));assert.equal((marginWindows(marginRows) as any).windows["10d"].short_balance_change_lots,20);
assert.equal((securitiesLendingWindows(lend) as any).windows["1d"].net_borrowed_shares,80);assert.equal((sblShortSaleWindows(otcSbl) as any).windows["1d"].sold_volume_shares,3000);
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const read=(p:string)=>fs.readFileSync(path.join(root,p),"utf8");
const source=read("src/v6/tw-market-data-github.ts");assert.match(source,/diamond-tw-market-data\/v2\.0\.0-github/);assert.match(source,/TaiwanStockInstitutionalInvestorsBuySell/);assert.match(source,/TaiwanStockMarginPurchaseShortSale/);assert.doesNotMatch(source,/TaiwanStockPrice/);assert.match(source,/GITHUB_ONLY/);assert.doesNotMatch(source,/D1Database|RESEARCH_DB|tw_market_data_snapshot_d1/);
const tools=read("src/v6/tw-market-data-tools.ts");for(const name of ["get_tw_market_data_contract","get_tw_institutional_flow","get_tw_margin_short","get_tw_securities_lending","get_tw_sbl_short_sale","get_tw_market_data_bundle","get_tw_market_data_status"])assert.match(tools,new RegExp(`registerTool\\(\\"${name}\\"`));assert.match(tools,/D1\/R2 forbidden/);assert.match(tools,/r2_usage: "FORBIDDEN"/);
const index=read("src/index-v6.ts");assert.match(index,/version: "6\.17\.0"/);assert.match(index,/tools: 113/);assert.match(index,/GITHUB_ONLY_NO_D1_NO_R2/);assert.doesNotMatch(index,/syncDiamondCanonicalBatch|CANONICAL_SYNC_VERSION|source_transport_branch|diamond-data/);assert.match(index,/expected_layers: 8/);assert.match(index,/incremental_ready_monotonic_missing_only_retry/);assert.match(index,/keywayk09\/tv-papertrader/);
const wrangler=read("wrangler.jsonc");assert.doesNotMatch(wrangler,/d1_databases|r2_buckets|RESEARCH_DB/);assert.match(wrangler,/GITHUB_DATA_REPO/);assert.match(wrangler,/keywayk09\/tv-papertrader/);assert.match(wrangler,/GITHUB_DATA_BRANCH/);assert.match(wrangler,/"main"/);assert.doesNotMatch(wrangler,/"crons"|"triggers"/);
const store=read("src/v6/github-data-store.ts");assert.match(store,/DEFAULT_GITHUB_DATA_REPO = "keywayk09\/tv-papertrader"/);assert.match(store,/DEFAULT_GITHUB_DATA_BRANCH = "main"/);assert.doesNotMatch(store,/DEFAULT_GITHUB_DATA_REPO = "keywayk09\/taistock-mcp"|DEFAULT_GITHUB_DATA_BRANCH = "diamond-data"/);
assert.equal(fs.existsSync(path.join(root,"src/v6/github-canonical-sync.ts")),false);
assert.equal(fs.existsSync(path.join(root,".github/workflows/market-data-github-archive.yml")),false);
const capture=read("scripts/capture-tw-market-data.ts");assert.match(capture,/market-data-incremental-controller/);assert.match(capture,/dueLayerKeys/);assert.match(capture,/mergeReadyMonotonic/);assert.match(capture,/TWSE_HOLIDAY_SCHEDULE/);assert.match(capture,/NO_TRADING_DAY/);assert.match(capture,/MARKET_DATA_FINAL_AUDIT/);assert.doesNotMatch(capture,/if\(ready<expected\.length\)process\.exitCode=2/);
for(const marker of ["TWT72U","TWT93U","tpex_margin_sbl","tpex_short_sell","T86","MI_MARGN"])assert.match(capture,new RegExp(marker));assert.match(capture,/data\/market-data\/raw/);assert.match(capture,/data\/market-data\/daily/);assert.match(capture,/data\/market-data\/index/);assert.match(capture,/data\/market-calendar/);
console.log("P19.3 incremental official-first GitHub-only Taiwan market data contract tests passed");
