export const RESEARCH_VNEXT_ATOMIC_DEPLOY_AUTHORIZATION = Object.freeze({
  schema: "RESEARCH_VNEXT_ATOMIC_DEPLOY_AUTHORIZATION_V1",
  phase: "DESIGN_ONLY_EXECUTION_BLOCKED",
  workflow_mode: "MANUAL_ONLY_REQUIRED",
  required_confirmation: "EXECUTE_ATOMIC_VNEXT_PRODUCTION",
  expected_sha: "EXACT_40_HEX_REQUIRED",
  oauth_kv: "EXISTING_SECRET_INPUT_ONLY",
  predeploy_snapshot: "ACTIVE_DEPLOYMENT_AND_VERSION_REQUIRED",
  cron_snapshot: "EXACT_PRE_POST_MATCH_REQUIRED",
  protected_exports: Object.freeze(["MyMCP", "FamilyMCP"]),
  do_lifecycle_change: "FORBIDDEN_FOR_THIS_CUTOVER",
  deploy_semantics: "ATOMIC_IMMEDIATE_100_PERCENT",
  rollback: Object.freeze({
    mode: "EXACT_VERSION_ID_ONLY",
    target: "PREDEPLOY_ACTIVE_VERSION_REQUIRED",
    allowed_only_if: "NO_DO_LIFECYCLE_CHANGE_AND_BINDINGS_STILL_VALID",
    automatic: false,
    on_uncertainty: "FAIL_CLOSED_MANUAL_INTERVENTION",
  }),
  postdeploy_probe: "READ_ONLY_PRODUCTION_PROBE_REQUIRED",
  owner_tool_count: 123,
  owner_abi_sha256: "00cdcc742cf147263e138561a59003ed9c2e67b6c3ae115a38764dea58c2735d",
  legacy_retirement: "BLOCKED_UNTIL_PRODUCTION_SWITCH_STABLE",
  production_deploy_authorized: false,
  production_mutation: "NONE",
} as const);
