import { dataKey, readGitHubJson, readGitHubText, updateGitHubJson } from "./github-data-store.ts";

export const GITHUB_USER_DATA_VERSION = "diamond-user-data/v1-github";

function nowIso(){return new Date().toISOString();}
async function namedPath(prefix:string,name:string){return `data/user/${prefix}/${await dataKey(name)}.json`;}

export type WatchItem={symbol:string;note:string;tags:string[];target_price?:number;stop_price?:number;added_at?:string;updated_at?:string};
export type Watchlist={schema_version:string;name:string;description:string;created_at:string;updated_at:string;items:WatchItem[]};

export async function loadWatchlist(env:Env,name:string){const read=await readGitHubJson<Watchlist>(env,await namedPath("watchlists",name));if(!read.value)throw new Error(`找不到觀察清單：${name}`);return read.value;}
export async function saveWatchlist(env:Env,input:{name:string;description:string;mode:"merge"|"replace";items:WatchItem[]}){const path=await namedPath("watchlists",input.name),now=nowIso();await updateGitHubJson<Watchlist>(env,{path,defaultValue:{schema_version:GITHUB_USER_DATA_VERSION,name:input.name,description:input.description,created_at:now,updated_at:now,items:[]},message:`data(watchlist): ${input.name}`,merge:(current)=>{const base=input.mode==="replace"?[]:current.items;const map=new Map(base.map(x=>[x.symbol,x]));for(const item of input.items){const old=map.get(item.symbol);map.set(item.symbol,{...old,...item,added_at:old?.added_at??now,updated_at:now});}return{...current,schema_version:GITHUB_USER_DATA_VERSION,name:input.name,description:input.description,updated_at:now,items:[...map.values()].sort((a,b)=>a.symbol.localeCompare(b.symbol))};}});return await loadWatchlist(env,input.name);}
export async function removeWatchlistItems(env:Env,name:string,symbols:string[]){const path=await namedPath("watchlists",name);await updateGitHubJson<Watchlist>(env,{path,defaultValue:{schema_version:GITHUB_USER_DATA_VERSION,name,description:"",created_at:nowIso(),updated_at:nowIso(),items:[]},message:`data(watchlist): remove ${name}`,merge:(current)=>({...current,updated_at:nowIso(),items:current.items.filter(x=>!symbols.includes(x.symbol))})});return await loadWatchlist(env,name);}

type SnapshotStore={schema_version:string;name:string;updated_at:string;snapshots:Record<string,any[]>};
export async function saveWatchlistSnapshot(env:Env,name:string,date:string,rows:any[]){const path=await namedPath("watchlist-snapshots",name);await updateGitHubJson<SnapshotStore>(env,{path,defaultValue:{schema_version:GITHUB_USER_DATA_VERSION,name,updated_at:"",snapshots:{}},message:`data(watchlist): snapshot ${name} ${date}`,merge:(current)=>({...current,updated_at:nowIso(),snapshots:{...current.snapshots,[date]:rows}})});}
export async function getWatchlistChanges(env:Env,name:string){const read=await readGitHubJson<SnapshotStore>(env,await namedPath("watchlist-snapshots",name));const snapshots=read.value?.snapshots??{},dates=Object.keys(snapshots).sort().reverse().slice(0,2);if(dates.length<2)throw new Error("至少需要在兩個不同日期執行 scan_saved_watchlist 才能比較變化");return{latestDate:dates[0],previousDate:dates[1],latest:snapshots[dates[0]]??[],previous:snapshots[dates[1]]??[]};}

type StockEvent={id:number;symbol:string;event_type:string;event_date:string;source:string;title:string;payload:Record<string,unknown>;created_at:string;outcome?:Record<string,unknown>|null};
type EventStore={schema_version:string;next_id:number;updated_at:string;events:StockEvent[]};
const EVENT_PATH="data/research/stock-events/index.json";
export async function recordStockEvent(env:Env,input:Omit<StockEvent,"id"|"created_at"|"outcome">){let created:StockEvent|null=null;await updateGitHubJson<EventStore>(env,{path:EVENT_PATH,defaultValue:{schema_version:GITHUB_USER_DATA_VERSION,next_id:1,updated_at:"",events:[]},message:`data(events): ${input.symbol} ${input.event_type}`,merge:(current)=>{const event:StockEvent={id:current.next_id,...input,created_at:nowIso(),outcome:null};created=event;return{...current,next_id:current.next_id+1,updated_at:event.created_at,events:[...current.events,event]};}});return created!;}
export async function listStockEvents(env:Env,filters:{symbol?:string;event_type?:string;limit?:number;from?:string;event_id?:number;without_outcome?:boolean}={}){const read=await readGitHubJson<EventStore>(env,EVENT_PATH);let rows=read.value?.events??[];if(filters.symbol)rows=rows.filter(x=>x.symbol===filters.symbol);if(filters.event_type)rows=rows.filter(x=>x.event_type===filters.event_type);if(filters.from)rows=rows.filter(x=>x.event_date>=filters.from!);if(filters.event_id)rows=rows.filter(x=>x.id===filters.event_id);if(filters.without_outcome)rows=rows.filter(x=>!x.outcome);rows=[...rows].sort((a,b)=>b.event_date.localeCompare(a.event_date)||b.id-a.id);return rows.slice(0,Math.max(1,Math.min(500,Number(filters.limit??100))));}
export async function saveEventOutcome(env:Env,eventId:number,outcome:Record<string,unknown>){await updateGitHubJson<EventStore>(env,{path:EVENT_PATH,defaultValue:{schema_version:GITHUB_USER_DATA_VERSION,next_id:1,updated_at:"",events:[]},message:`data(events): outcome ${eventId}`,merge:(current)=>({...current,updated_at:nowIso(),events:current.events.map(x=>x.id===eventId?{...x,outcome:{...outcome,evaluated_at:nowIso()}}:x)})});}

export async function findEventPatterns(env:Env,symbol:string|undefined,minSamples:number){const rows=await listStockEvents(env,{symbol,limit:500});const groups=new Map<string,StockEvent[]>();for(const row of rows){if(!row.outcome)continue;const list=groups.get(row.event_type)??[];list.push(row);groups.set(row.event_type,list);}const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;return[...groups.entries()].filter(([,xs])=>xs.length>=minSamples).map(([event_type,xs])=>{const val=(k:string)=>xs.map(x=>Number(x.outcome?.[k])).filter(Number.isFinite);const r20=val("return_20d");return{event_type,samples:xs.length,avg_return_5d:avg(val("return_5d")),avg_return_20d:avg(r20),avg_return_60d:avg(val("return_60d")),avg_mfe_20d:avg(val("mfe_20d")),avg_mae_20d:avg(val("mae_20d")),positive_20d_rate:r20.length?100*r20.filter(x=>x>0).length/r20.length:null};}).sort((a,b)=>(b.avg_return_20d??-Infinity)-(a.avg_return_20d??-Infinity));}

type Portfolio={schema_version:string;name:string;created_at:string|null;updated_at:string|null;positions:any[]};
export async function savePortfolio(env:Env,name:string,mode:"merge"|"replace",positions:any[]){const path=await namedPath("portfolios",name),now=nowIso();await updateGitHubJson<Portfolio>(env,{path,defaultValue:{schema_version:GITHUB_USER_DATA_VERSION,name,created_at:now,updated_at:now,positions:[]},message:`data(portfolio): ${name}`,merge:(current)=>{const base=mode==="replace"?[]:current.positions,map=new Map(base.map((x:any)=>[x.symbol,x]));for(const x of positions)map.set(x.symbol,{...map.get(x.symbol),...x,updated_at:now});return{...current,name,updated_at:now,positions:[...map.values()].sort((a,b)=>String(a.symbol).localeCompare(String(b.symbol)))};}});return await getPortfolio(env,name);}
export async function getPortfolio(env:Env,name:string){const read=await readGitHubJson<Portfolio>(env,await namedPath("portfolios",name));return read.value??{schema_version:GITHUB_USER_DATA_VERSION,name,created_at:null,updated_at:null,positions:[]};}

export async function probeGitHubDataRead(env:Env){const started=Date.now();const read=await readGitHubText(env,"README.md");return{latency_ms:Date.now()-started,latest:read.exists?read.sha:null,storage:"GITHUB_ONLY"};}
