import { GitHubDataStoreError, listIndexedRecords, putIndexedImmutableRecord, readIndexedRecord } from "./github-data-store.ts";
import { querySupplyChainSnapshot, validateSupplyChainSnapshot, type SupplyChainSnapshotInput } from "./supply-chain-graph.ts";

export const SUPPLY_CHAIN_DATA_PLANE_VERSION = "diamond-supply-chain-data-plane/v2.0.0-github";

export class SupplyChainDataPlaneError extends Error {
  readonly code:string; readonly detail?:Record<string,unknown>;
  constructor(code:string,message:string,detail?:Record<string,unknown>){super(message);this.name="SupplyChainDataPlaneError";this.code=code;this.detail=detail;}
}
function requiredText(value:unknown,field:string,max=1000){const text=String(value??"").trim();if(!text)throw new SupplyChainDataPlaneError("INVALID_INPUT",`${field} is required`);if(text.length>max)throw new SupplyChainDataPlaneError("INVALID_INPUT",`${field} is too long`);return text;}
function hashFromVersion(datasetVersion:string){const match=/^sha256:([0-9a-f]{64})$/.exec(datasetVersion);if(!match)throw new SupplyChainDataPlaneError("INVALID_DATASET_VERSION","dataset_version must be sha256:<64 hex>");return match[1];}
function wrapStore(error:unknown):never{if(error instanceof GitHubDataStoreError)throw new SupplyChainDataPlaneError(error.code,error.message,error.detail);throw error;}
export async function ensureSupplyChainDataPlaneSchema(_env:Env){ /* GitHub-only persistence. */ }

export async function archiveSupplyChainSnapshot(env:Env,input:{snapshot:SupplyChainSnapshotInput;archive_actor:string;review_note?:string;human_approved:boolean}){
  if(!input?.human_approved)throw new SupplyChainDataPlaneError("HUMAN_APPROVAL_REQUIRED","archiving a research supply-chain snapshot requires explicit human approval");
  const actor=requiredText(input.archive_actor,"archive_actor",200),review_note=input.review_note?requiredText(input.review_note,"review_note",2000):null,validated=await validateSupplyChainSnapshot(input.snapshot),hash=hashFromVersion(validated.dataset_version),archived_at=new Date().toISOString();
  const snapshot={as_of:validated.as_of,source_dataset:validated.source_dataset??undefined,entities:validated.entities,evidence:validated.evidence,edges:validated.edges};
  const record={archive_schema:SUPPLY_CHAIN_DATA_PLANE_VERSION,snapshot,dataset_id:validated.dataset_id,dataset_version:validated.dataset_version,content_sha256:hash,formal_research_eligible:validated.formal_research_eligible,entity_count:validated.entity_count,instrument_count:validated.instrument_count,evidence_count:validated.evidence_count,edge_count:validated.edge_count,verified_edge_count:validated.verified_or_corroborated_edge_count,candidate_edge_count:validated.candidate_edge_count,archived_at,archive_actor:actor,review_note,storage:"GITHUB_ONLY"};
  const symbols=[...new Set(validated.entities.flatMap((e)=>e.instruments.map((i)=>String(i.symbol).toUpperCase())))];
  const markets=[...new Set(validated.entities.flatMap((e)=>e.instruments.map((i)=>String(i.market).toUpperCase())))];
  try{const w=await putIndexedImmutableRecord(env,{collection:"research/supply-chain",key:validated.dataset_version,record,metadata:{dataset_version:validated.dataset_version,dataset_id:validated.dataset_id,as_of:validated.as_of,source_dataset:validated.source_dataset??null,formal_research_eligible:validated.formal_research_eligible,symbols,markets}});return{ok:true as const,idempotent:w.idempotent,dataset_id:validated.dataset_id,dataset_version:validated.dataset_version,storage:"GITHUB_ONLY" as const,formal_research_eligible:validated.formal_research_eligible,archived_at};}catch(e){wrapStore(e);}
}

export async function loadArchivedSupplyChainSnapshot(env:Env,datasetVersion:string){const version=requiredText(datasetVersion,"dataset_version",80);hashFromVersion(version);const row=await readIndexedRecord<any>(env,"research/supply-chain",version);if(!row)throw new SupplyChainDataPlaneError("DATASET_NOT_FOUND","supply-chain dataset_version is not archived",{dataset_version:version});const validated=await validateSupplyChainSnapshot(row.snapshot as SupplyChainSnapshotInput);if(validated.dataset_version!==version||validated.dataset_id!==String(row.dataset_id)||String(row.content_sha256)!==hashFromVersion(version))throw new SupplyChainDataPlaneError("ARCHIVE_HASH_MISMATCH","archived payload no longer matches indexed immutable identity",{dataset_version:version});return{index:row,snapshot:validated,storage:"GITHUB_ONLY" as const};}

export async function queryArchivedSupplyChain(env:Env,input:{dataset_version:string;anchor:string;direction?:"UPSTREAM"|"DOWNSTREAM"|"BOTH";max_depth?:number;include_candidates?:boolean}){const loaded=await loadArchivedSupplyChainSnapshot(env,input.dataset_version);return querySupplyChainSnapshot({as_of:loaded.snapshot.as_of,source_dataset:loaded.snapshot.source_dataset??undefined,entities:loaded.snapshot.entities,evidence:loaded.snapshot.evidence,edges:loaded.snapshot.edges,anchor:input.anchor,direction:input.direction,max_depth:input.max_depth,include_candidates:input.include_candidates});}

export async function findSupplyChainDatasets(env:Env,input:{symbol?:string;market?:string;as_of_lte?:string;formal_only?:boolean;limit?:number}){const symbol=input.symbol?requiredText(input.symbol,"symbol",40).toUpperCase():undefined,market=input.market?requiredText(input.market,"market",40).toUpperCase():undefined,asOf=input.as_of_lte?requiredText(input.as_of_lte,"as_of_lte",10):undefined,limit=Math.max(1,Math.min(100,Math.floor(Number(input.limit??20))));const datasets=await listIndexedRecords<any>(env,"research/supply-chain",(e)=>(!asOf||String(e.as_of)<=asOf)&&(!input.formal_only||e.formal_research_eligible===true)&&(!symbol||Array.isArray(e.symbols)&&e.symbols.includes(symbol))&&(!market||Array.isArray(e.markets)&&e.markets.includes(market)),limit);datasets.sort((a,b)=>String(b.as_of).localeCompare(String(a.as_of))||String(b.archived_at).localeCompare(String(a.archived_at)));return{ok:true as const,storage:"GITHUB_ONLY" as const,count:datasets.length,datasets};}
